// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeD1LVKkP3J0QZEaaH0bga7YkuuC7tjX8',
    appId: '1:352152923888:web:8f90415af830397da7dc35',
    messagingSenderId: '352152923888',
    projectId: 'shopping-list-app-b4849',
    authDomain: 'shopping-list-app-b4849.firebaseapp.com',
    storageBucket: 'shopping-list-app-b4849.firebasestorage.app',
    measurementId: 'G-JMRC3NFTJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5-8nrDmZTJBYwXsi5QkRuaoLMO-HY2E',
    appId: '1:352152923888:android:6b679c36d675f306a7dc35',
    messagingSenderId: '352152923888',
    projectId: 'shopping-list-app-b4849',
    storageBucket: 'shopping-list-app-b4849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmN48K8Ql327SkQUyoFrG4uOs4ZsZtclw',
    appId: '1:352152923888:ios:afe6c0a61fe103c8a7dc35',
    messagingSenderId: '352152923888',
    projectId: 'shopping-list-app-b4849',
    storageBucket: 'shopping-list-app-b4849.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmN48K8Ql327SkQUyoFrG4uOs4ZsZtclw',
    appId: '1:352152923888:ios:afe6c0a61fe103c8a7dc35',
    messagingSenderId: '352152923888',
    projectId: 'shopping-list-app-b4849',
    storageBucket: 'shopping-list-app-b4849.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeD1LVKkP3J0QZEaaH0bga7YkuuC7tjX8',
    appId: '1:352152923888:web:1b51dbdf67d763c8a7dc35',
    messagingSenderId: '352152923888',
    projectId: 'shopping-list-app-b4849',
    authDomain: 'shopping-list-app-b4849.firebaseapp.com',
    storageBucket: 'shopping-list-app-b4849.firebasestorage.app',
    measurementId: 'G-WY2B5Y8PY5',
  );

}